export type Stats = {
  Total: number
  All: number
  AllUpdated: string
  Countries: number
  CountriesUpdated: string
  ByCountry: number
  ByCountryUpdated: string
  ByCountryLive: number
  ByCountryLiveUpdated: string
  ByCountryTotal: number
  ByCountryTotalUpdated: string
  DayOne: number
  DayOneUpdated: string
  DayOneLive: number
  DayOneLiveUpdated: string
  DayOneTotal: number
  DayOneTotalUpdated: string
  LiveCountryStatus: number
  LiveCountryStatusUpdated: string
  LiveCountryStatusAfterDate: number
  LiveCountryStatusAfterDateUpdated: string
  Stats: number
  StatsUpdated: string
  Default: number
  DefaultUpdated: string
  SubmitWebhook: number
  SubmitWebhookUpdated: string
  Summary: number
  SummaryUpdated: string
}
